usethis::use_package("rlang", min_version = TRUE)
usethis::use_package("tibble", min_version = TRUE)
usethis::use_package("dplyr", min_version = TRUE)
usethis::use_package("purrr", min_version = TRUE)
usethis::use_package("magrittr", min_version = TRUE)
usethis::use_package("tidyselect", min_version = TRUE)
usethis::use_package("tidyr", min_version = TRUE)
usethis::use_package("readr", min_version = TRUE)
usethis::use_package("lubridate", min_version = TRUE)
usethis::use_package("httr", min_version = TRUE)
usethis::use_package("curl", min_version = TRUE)
usethis::use_package("xml2", min_version = TRUE)
usethis::use_package("rvest", min_version = TRUE)
usethis::use_package("utils", min_version = TRUE)
usethis::use_package("countrycode", min_version = TRUE)
usethis::use_package("R6", min_version = TRUE)
usethis::use_package("classInt", min_version = TRUE)
usethis::use_package("htmltools", min_version = TRUE)
usethis::use_package("leaflet", min_version = TRUE)
usethis::use_package("dygraphs", min_version = TRUE)
usethis::use_package("xts", min_version = TRUE)
usethis::use_package("ggplot2", min_version = TRUE)
usethis::use_package("jsonlite", min_version = TRUE)
usethis::use_package("stringr", min_version = TRUE)
usethis::use_package("tabulizer", min_version = TRUE)
usethis::use_build_ignore("devtools_history.R")
usethis::use_data(iso3c, world_spdf, internal = TRUE, overwrite = TRUE)
usethis::use_vignette("how-to-use-the-rccs-package")
